In [11]:
import wget
import os


data_url = "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
absolute_path = os.getcwd()
project_path = "data/DogsAndCats/"
file_name = "DogAndCats.zip"
path = os.path.join(absolute_path, project_path)

if not os.path.exists(os.path.join(path, file_name)):
    os.mkdir(path)
    wget.download(data_url, os.path.join(path, file_name))

In [12]:
import zipfile

file_to_extract = os.path.join(path, file_name)
folder_with_images = "PetImages"
if not os.path.isdir(os.path.join(path, folder_with_images)):
    with zipfile.ZipFile(file_to_extract, 'r') as zip_ref:
        zip_ref.extractall(path)

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import sys
from tqdm import tqdm

DATADIR = os.path.join(path, folder_with_images)
IMG_SIZE = 100
CATEGORIES = ["Dog", "Cat"]

training_data = []

def create_training_data():
    for category in CATEGORIES:

        categoty_path = os.path.join(DATADIR,category)  # create path to dogs and cats
        class_num = CATEGORIES.index(category)  # get the classification  (0 or a 1). 0=dog 1=cat

        for img in tqdm(os.listdir(categoty_path)):  # iterate over each image per dogs and cats
            try:
                img_array = cv2.imread(os.path.join(categoty_path, img), cv2.IMREAD_GRAYSCALE)  # convert to array
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))  # resize to normalize data size
                training_data.append([new_array, class_num])  # add this to our training_data
            except Exception as e:
                pass
                #print("general exception", e, os.path.join(categoty_path, img))

create_training_data()

print(len(training_data))





  0%|          | 0/12501 [00:00<?, ?it/s]



  1%|          | 68/12501 [00:00<00:18, 669.01it/s]



  1%|          | 142/12501 [00:00<00:17, 688.19it/s]



  2%|▏         | 243/12501 [00:00<00:16, 759.92it/s]



  3%|▎         | 320/12501 [00:00<00:16, 760.81it/s]



  3%|▎         | 395/12501 [00:00<00:16, 756.31it/s]



  4%|▍         | 480/12501 [00:00<00:15, 781.04it/s]



  5%|▍         | 570/12501 [00:00<00:14, 809.82it/s]



  5%|▌         | 662/12501 [00:00<00:14, 839.40it/s]



  6%|▌         | 749/12501 [00:00<00:13, 848.20it/s]



  7%|▋         | 835/12501 [00:01<00:13, 850.20it/s]



  7%|▋         | 919/12501 [00:01<00:13, 840.41it/s]



  8%|▊         | 1005/12501 [00:01<00:13, 844.59it/s]



  9%|▊         | 1093/12501 [00:01<00:13, 853.19it/s]



  9%|▉         | 1184/12501 [00:01<00:13, 865.14it/s]



 10%|█         | 1273/12501 [00:01<00:12, 872.42it/s]



 11%|█         | 1361/12501 [00:01<00:12, 863.30it/s]



 12%|█▏        | 1448/12501 [00:01<00:13, 796.29it/

 75%|███████▌  | 9429/12501 [00:12<00:05, 609.80it/s]



 76%|███████▌  | 9491/12501 [00:12<00:05, 594.14it/s]



 76%|███████▋  | 9551/12501 [00:12<00:05, 581.24it/s]



 77%|███████▋  | 9610/12501 [00:12<00:04, 582.90it/s]



 77%|███████▋  | 9669/12501 [00:13<00:05, 486.39it/s]



 78%|███████▊  | 9727/12501 [00:13<00:05, 510.61it/s]



 78%|███████▊  | 9800/12501 [00:13<00:04, 559.18it/s]



 79%|███████▉  | 9864/12501 [00:13<00:04, 578.42it/s]



 79%|███████▉  | 9925/12501 [00:13<00:04, 579.48it/s]



 80%|███████▉  | 9985/12501 [00:13<00:04, 582.98it/s]



 80%|████████  | 10045/12501 [00:13<00:04, 573.30it/s]



 81%|████████  | 10104/12501 [00:13<00:04, 562.66it/s]



 81%|████████▏ | 10167/12501 [00:13<00:04, 579.44it/s]



 82%|████████▏ | 10230/12501 [00:14<00:03, 593.73it/s]



 82%|████████▏ | 10290/12501 [00:14<00:03, 589.71it/s]



 83%|████████▎ | 10351/12501 [00:14<00:03, 593.30it/s]



 83%|████████▎ | 10411/12501 [00:14<00:03, 582.40it/s]


 57%|█████▋    | 7098/125

 16%|█▌        | 1966/12501 [00:06<00:30, 342.33it/s]



 16%|█▌        | 2011/12501 [00:06<00:28, 364.16it/s]



 16%|█▋        | 2049/12501 [00:06<00:30, 345.03it/s]



 17%|█▋        | 2085/12501 [00:06<00:35, 289.96it/s]



 17%|█▋        | 2117/12501 [00:07<00:34, 297.71it/s]



 17%|█▋        | 2149/12501 [00:07<00:37, 274.71it/s]



 17%|█▋        | 2180/12501 [00:07<00:36, 283.22it/s]



 18%|█▊        | 2213/12501 [00:07<00:35, 293.39it/s]



 18%|█▊        | 2244/12501 [00:07<00:34, 298.10it/s]



 18%|█▊        | 2279/12501 [00:07<00:33, 307.29it/s]



 18%|█▊        | 2311/12501 [00:07<00:33, 303.25it/s]



 19%|█▉        | 2348/12501 [00:07<00:31, 319.44it/s]



 19%|█▉        | 2395/12501 [00:07<00:28, 352.51it/s]



 20%|█▉        | 2444/12501 [00:07<00:26, 383.41it/s]



 20%|█▉        | 2488/12501 [00:08<00:25, 398.16it/s]



 20%|██        | 2546/12501 [00:08<00:22, 439.09it/s]



 21%|██        | 2593/12501 [00:08<00:22, 439.56it/s]



 21%|██        | 2651/12501 [00

 64%|██████▍   | 8031/12501 [00:19<00:08, 529.73it/s]



 65%|██████▍   | 8085/12501 [00:19<00:08, 510.01it/s]



 65%|██████▌   | 8151/12501 [00:19<00:07, 546.71it/s]



 66%|██████▌   | 8212/12501 [00:19<00:07, 563.42it/s]



 66%|██████▌   | 8271/12501 [00:19<00:07, 570.94it/s]



 67%|██████▋   | 8329/12501 [00:19<00:07, 550.54it/s]



 67%|██████▋   | 8386/12501 [00:19<00:07, 553.70it/s]



 68%|██████▊   | 8442/12501 [00:19<00:07, 545.42it/s]



 68%|██████▊   | 8497/12501 [00:19<00:07, 522.85it/s]



 68%|██████▊   | 8550/12501 [00:19<00:07, 501.69it/s]



 69%|██████▉   | 8601/12501 [00:20<00:07, 503.73it/s]



 69%|██████▉   | 8652/12501 [00:20<00:07, 499.50it/s]



 70%|██████▉   | 8703/12501 [00:20<00:07, 479.03it/s]



 70%|███████   | 8755/12501 [00:20<00:07, 489.46it/s]



 70%|███████   | 8813/12501 [00:20<00:07, 511.93it/s]



 71%|███████   | 8865/12501 [00:20<00:07, 508.21it/s]



 71%|███████▏  | 8917/12501 [00:20<00:07, 504.03it/s]



 72%|███████▏  | 8968/12501 [00

24946


In [6]:
import random

random.shuffle(training_data)
for sample in training_data[:10]:
    print(sample[1])

In [19]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)


X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)

[[[[181]
   [221]
   [207]
   ...
   [182]
   [192]
   [193]]

  [[225]
   [240]
   [233]
   ...
   [179]
   [192]
   [191]]

  [[111]
   [120]
   [129]
   ...
   [184]
   [192]
   [169]]

  ...

  [[255]
   [255]
   [255]
   ...
   [197]
   [203]
   [243]]

  [[254]
   [255]
   [255]
   ...
   [229]
   [242]
   [253]]

  [[255]
   [255]
   [255]
   ...
   [244]
   [250]
   [240]]]]


In [21]:
import pickle

DATA_FILE = "PreparedDogAndCats"
DIR_TO_DATA_FILES = os.path.join(os.getcwd(), DATA_FILE)
X_PICKLE = os.path.join(DIR_TO_DATA_FILES, "X.pickle")
Y_PICKLE = os.path.join(DIR_TO_DATA_FILES, "Y.pickle")

if not os.path.isdir(DIR_TO_DATA_FILES):
    os.mkdir(DIR_TO_DATA_FILES)
    pickle_out = open(X_PICKLE,"wb")
    pickle.dump(X, pickle_out)
    pickle_out.close()

    pickle_out = open(Y_PICKLE,"wb")
    pickle.dump(y, pickle_out)
    pickle_out.close()


In [22]:
pickle_in = open(Y_PICKLE,"rb")
X = pickle.load(pickle_in)

pickle_in = open(Y_PICKLE,"rb")
y = pickle.load(pickle_in)